addons:
  ssh_known_hosts: github.com # required to allow git clone certicates repo

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  bundler: true
  directories:
    - $HOME/.npm

matrix:
  include:
    - stage: Deploy iOS 🍏
      os: osx
      osx_image: xcode12.5
      language: objective-c
      node_js: false

      before_install:
        - nvm install 14.16.1 # enforce using same version as local builds
        - npm i -g npm@6.14.12 # enforce using same version as local builds
        - nvm alias default 14.16.1 # otherwise sentry-cli will fail with a cryptic error
        - node --version
        - npm --version
        - gem install fastlane --version 2.118.1 --no-document --quiet

        # Required after upgrading to RN v0.59.10, otherwise Sentry code inside
        # "Bundle React Native code and images" build phase fails.
        # See https://github.com/getsentry/sentry-react-native/issues/135#issuecomment-447366274
        - brew install watchman

        # Decrypt SSH deploy key for GitHub certificates repo and add to agent
        - openssl aes-256-cbc -K $encrypted_89b232081b73_key -iv $encrypted_89b232081b73_iv
          -in github_deploy_key.enc -out github_deploy_key -d
        - chmod 600 github_deploy_key
        - eval $(ssh-agent -s)
        - ssh-add github_deploy_key

        # Decrypt Sentry properties file and add copy to /ios directory
        - openssl aes-256-cbc -K $encrypted_ace616ffe366_key -iv $encrypted_ace616ffe366_iv
          -in sentry.properties.enc -out ios/sentry.properties -d

      install:
        - npm ci || travis_terminate 1

      script:
        # Create .env file
        - npm run env || travis_terminate 1
        - cat .env

        # Supposedly this shouldn't be necesary, possible RN bug?
        # See https://github.com/facebook/react-native/issues/18472
        - npm i -g react-native-cli@2.0.1
        - react-native info
        - npm run ios:bundle -- --dev false || travis_terminate 1

        - npm run ios:beta

    - stage: Deploy Android 🤖
      language: android
      jdk: oraclejdk8
      node_js: false
      android:
        components:
          - tools
          - platform-tools
          - android-28
          - extra-google-m2repository
          - extra-google-google_play_services

      before_install:
        - nvm install 14.16.1 # enforce using same version as local builds
        - npm i -g npm@6.14.12 # enforce using same version as local builds
        - nvm alias default 14.16.1 # otherwise sentry-cli will fail with a cryptic error
        - node --version
        - npm --version
        - gem install fastlane --version 2.118.1 --no-document --quiet
        - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3" # accept android licenses

        # After upgrading to RN v0.59.10, we need to increase the number of inotify watches
        # See https://github.com/fbsamples/f8app/issues/55#issuecomment-228995680
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

        # Decrypt Sentry properties file and add copy to /android directory
        - openssl aes-256-cbc -K $encrypted_ace616ffe366_key -iv $encrypted_ace616ffe366_iv
          -in sentry.properties.enc -out android/sentry.properties -d

        - openssl aes-256-cbc -K $encrypted_2cfeec998f68_key -iv $encrypted_2cfeec998f68_iv
          -in metronome-wallet.keystore.enc -out android/metronome-wallet.keystore -d

        - openssl aes-256-cbc -K $encrypted_5573d999f481_key -iv $encrypted_5573d999f481_iv
          -in MetronomeWalletSigningKey.json.enc -out MetronomeWalletSigningKey.json -d

      install:
        - npm ci || travis_terminate 1

      script:
        # Create .env file
        - npm run env || travis_terminate 1
        - cat .env

        - npm run gradle-properties
        - npm run android:beta
