fastlane_version "2.118.1"
begin
  setup_travis
  xcversion(version: "10.1")
rescue
  puts "Could not create keychain and set Xcode version"
end

platform :ios do
  desc "Fetch certificates and provisioning profiles"
  lane :setup_certificates do
    match(type: "development")
    match(type: "appstore")
  end

  desc "Build the iOS application."
  private_lane :build do |options|
    setup_certificates
    puts "Incrementing version number to " + options[:version]
    increment_version_number(
      version_number: options[:version],
      xcodeproj: "./ios/MetronomeWallet.xcodeproj",
    )
    increment_build_number(
      build_number: ENV["TRAVIS_BUILD_NUMBER"],
      xcodeproj: "./ios/MetronomeWallet.xcodeproj",
    )
    gym(
      scheme: "MetronomeWallet",
      project: "./ios/MetronomeWallet.xcodeproj",
    )
  end

  desc "Ship to TestFlight."
  lane :beta do |options|
    build(options)
    # Deploy only if the commit is in branch master or develop.
    if (options[:TRAVIS_BRANCH] === "master" || options[:TRAVIS_BRANCH] === "develop") && options[:TRAVIS_PULL_REQUEST] === "false"
      pilot(
        skip_waiting_for_build_processing: true,
        app_identifier: "sh.autonomous.wallet.mobile",
        username: "pablo@bloq.com",
        verbose: true,
      )
    end
  end
end

platform :android do
  # Android Lanes
  desc "Build the Android application."
  private_lane :build do
    gradle(task: "clean", project_dir: "android/")
    gradle(task: "assemble", build_type: "Release", project_dir: "android/")
  end

  desc "Ship to Playstore Beta."
  lane :beta do |options|
    build(options)
    # Deploy only if the commit is in branch master or develop.
    if (options[:TRAVIS_BRANCH] === "master" || options[:TRAVIS_BRANCH] === "develop") && options[:TRAVIS_PULL_REQUEST] === "false"
      supply(
        track: "internal",
        json_key: "MetronomeWalletSigningKey.json",
        package_name: "sh.autonomous.wallet.mobile",
      )
    end
  end
end
