#!/bin/bash

if [ "$TRAVIS_BRANCH" = master ];
  then ENABLED_CHAINS=$PROD_CHAINS;
  else ENABLED_CHAINS=$TEST_CHAINS;
fi

echo "ENABLED_CHAINS are: " "$ENABLED_CHAINS"

cat > .env << EOF
ENABLED_CHAINS=$ENABLED_CHAINS
MORDOR_INDEXER_URL=$MORDOR_INDEXER_URL
MORDOR_NODE_URL=$MORDOR_NODE_URL
ROPSTEN_INDEXER_URL=$ROPSTEN_INDEXER_URL
ROPSTEN_NODE_URL=$ROPSTEN_NODE_URL
SENTRY_DSN=$SENTRY_DSN
TRACKING_ID=$TRACKING_ID
EOF
