#!/bin/bash

cat > android/gradle.properties << EOF
android.useDeprecatedNdk=true
android.enableAapt2=false
VERSION_NAME=$1
VERSION_CODE=$TRAVIS_BUILD_NUMBER
METRONOME_RELEASE_STORE_FILE=$METRONOME_RELEASE_STORE_FILE
METRONOME_RELEASE_STORE_PASSWORD=$METRONOME_RELEASE_STORE_PASSWORD
METRONOME_RELEASE_KEY_ALIAS=$METRONOME_RELEASE_KEY_ALIAS
METRONOME_RELEASE_KEY_PASSWORD=$METRONOME_RELEASE_KEY_PASSWORD
EOF
